O365/python-o365

O365/message.py

Enable support for email address to be passed in as a list of strings in setRecipients. As in issue #25.

Add email address string support to setRecipients

---

O365/event.py

Fix: Function description is SetAttendees while the function was named SetAttendee. Renamed the function to match the description
Add: Ability to set the timezone for the start of the meeting
Add: Ability to set the timezone for the end of the meeting
Add: Missing import for group, this is called by event.py to create a group object.
vent makes use of the group module on line 333 of this file. It was never imported and so that caused an error. Added group to the imports, this should relieve the issue.

Add event settings for timezones and type of event

---

O365/message.py

*NOT TESTED*
In regards to https://github.com/Narcolapser/python-o365/issues/43, I added the same try/catch that is in setBody, which will set the "Body" JSON key if it is not already set.

Add try/except for JSON body key

---

O365/cal.py

The calendar getEvents function is only able to bring in 10 events.  Modifying the url to add &$top=50 will allow 50 (which is the max per page for the 0365 api)

Ability to pull more than 10 events

---

O365/inbox.py

Currently on an Inbox instance initialization, if getNow is set to True, it leads to an attribute error on Line 53 since self.verify is defined after the call to getMessages().

Moved Inbox verify variable to be assigned before getMessages call

---

O365/attachment.py

imported path from os and used the path.join() function to get the correct path location for ones particular OS. This will make scripts written with this module also cross OS. This is a fix for issue #75.

Fixed save() to work on windows and linux

---

O365/fluent_message.py
O365/message.py
README.md

corrects all instances and variations of 'recieve' to 'receive'.
affects `Message` attribute "reciever" but is otherwise just in docstrings.

replace reciev -> receiv (spelling fix)

---

O365/handlers.py
O365/message.py

This is a pretty simple handler for Python's logging package. In my environment at work, we don't really have good access to an SMTP server, so I don't think logging's built-in SMTP handler will work for me. This new handler does work for me, however, as we use O365. I figured having a handler built into O365 might be nice for anyone else using it.
I worked using the language style you already have in message.py as best I could.
I also believe there was an issue with the default self.json assignment for O365.Message(). As far as I can tell, everything else that sets self.json or uses self.json expects 'Body' to be in the self.json dictionary itself, not nested under self.json['Message'], which is what was being done in __init__(). If you initialized with a JSON parameter or you used …

Logging handler

---

O365/connection.py
O365/fluent_inbox.py
O365/fluent_message.py

* Connection: Added HTTP 401 error message instead of throwing misleading error on json decode 
* Fluent message: removed print statement, added setCategory alias function
* Fluent inbox: added support for shared inbox, replaced redundant code with get_mailbox()

Support for fluent shared mailboxes, 401 error msg and more

---

O365/fluent_inbox.py
setup.py

As the title suggests:
* Added support for working with child folders in shared inboxes.
* Updated `setup.py` preparing for a new PyPI release based on [official guide](https://packaging.python.org/tutorials/packaging-projects/)
See new quick reference commands to build and upload at the bottom of `setup.py`

Support for shared inbox child folders and updated setup.py for PyPI

---

O365/connection.py

Add the ability to specify default headers used in future requests. For example this gives you the ability to set Connection.default_headers = {'Prefer': 'outlook.body-content-type="text"'}, to request to be sent text instead of html from outlook for future calls.
https://msdn.microsoft.com/en-us/office/office365/api/mail-rest-operations

Add the ability to specify default headers used in future requests.

---

O365/fluent_inbox.py
O365/fluent_message.py

Save oauth in message for later use.
Messages now use oauth if it's been set.
Use response.ok to determine if call succeeded.
Changed Content-type to Content-Type.
Response doc: http://docs.python-requests.org/en/master/api/#requests.Response

Use oauth in message calls

---

O365/connection.py

This will ensure that results returned are always of never of type dict and instead are of type MicroDict.
I ran into an issue using getSenderEmail where 'EmailAddress' failed because the dict would not recognize the element 'emailAddress' as the same. By converting dict's to MicroDict's this method works for me again.

Have values of type dict returned also be converted to type MicroDict.

---

O365/fluent_message.py

Use 2.0 version of the url if using OAuth, as the old urls don't work with an OAuth token using 2.0 scope

Message use 2.0 urls

---

O365/connection.py

Applications that are not set up for multi tenant must talk to a
different endpoint than "common". This adds an argument for this to
the Connection class (__init__).
Fix #184.

add tenant_id parameter to Connection class

---

O365/calendar.py

The "CalendarColor" names seem to start with a small not a capital "L".
To keep a consistent namescheme "MaxColor" and "Auto" should be renamed to "maxColor" and "auto", too.
( In row 1499 it is already "auto")
I encountered this problem when my code throwed the following error while trying to get a calendar:
```
>>> schedule = account.schedule()
>>> calendar = schedule.get_calendar(calendar_name='Heizung')
ValueError: 'lightGreen' is not a valid CalendarColors
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "<pyshell#9>", line 1, in <module>
calendar = schedule.get_calendar(calendar_name='Heizung')
File "E:\Programme\Python\Python3\lib\site-packages\O365\calendar.py", line 1849, in get_calendar
**{self._cloud_data_key: data}) …
```

Correcting CalendarColors names

---

O365/sharepoint.py

When the site class is being built from a parent site, in the cases of get_subsites, the parent main_resource does not need to be used, only the resource_prefix.
Closes #214 
Fix works when building a site directly from Sharepoint class and also from subsite class.  Functionality is as expected for the resulting site class no matter how it was built with this fix.

Use just resource_prefix if parent is a site

---

O365/sharepoint.py

Took a stab on adding some functionality that I have working on my O365 sharepoint.  Open to feedback on any way to make this better, but figured it was a start.  Review at your leisure.
Added a crosswalk between display name, and internal name for user defined columns in the list.  Added update_list_item to update a given listitem, and create_list_item to create a new list item.
Additions:
1. SharepointList.column_name_cw - dictionary of {display_name: internal_name} for user defined columns in a sharepoint list. (I have found this useful when doing things like list updates, additions, and pulling down detail)
2. SharepointList.update_list_item(item_id, update) - given an item id and dict of {internal column name: updated data} it will update the sharepoint list item, and return the …

Ability to create, and edit listitems in sharepoint

---

O365/calendar.py

When using the MSOffice365Protocol, a calendar.get_events() query fails with:
`ValueError: When 'include_recurring' is True you must provide a 'start' and
'end' datetimes inside a Query instance.` even when such a query is provided.
This is due to the fact the the case of the Filter is not the same between
protocols, and the code was assuming that some filters were in lower case.
Fixes #226

Fixes error message when doing calendar queries with MSOffice365Protocol

---

O365/message.py

`to_api_data()` will not serialize the `self.categories` property if you try to remove all categories from a message since `self.categories` evaluates to `False` for an empty list.
If `self.categories` has been modified, the `categories` string will be passed into `to_api_data()` from the `save_message()` function as the `restrict_keys` parameters.

fix bug for removing all categories from a message

---

O365/message.py

Found this bug while parsing mails. Just a minor change required in the way the attributes are queried.

Fix "keyerror" issue in beautifulsoup while checking attribute.

---

O365/message.py

This was throwing error when it was parsing flagged messages with no start and due date.

Fix error when flag does not have start and due date

---

O365/excel.py

See the following thread: https://github.com/microsoftgraph/microsoft-graph-docs/issues/4818
The current table row deletion doesn't work and returns the following "Error Message: Resource not found for the segment 'delete'."
The API method here does work: 
https://docs.microsoft.com/en-us/graph/api/resources/excel?view=graph-rest-beta#delete-table-row
I've updated the code and it now works.

Fix Table Delete Row method to match alternative docs

---

O365/excel.py

Similar to my fix to delete rows, I have another fix for deleting tables 
See: https://github.com/microsoftgraph/microsoft-graph-docs/issues/4188
Using the Post for deleting doesn't work (POST /workbook/tables/{id|name}/delete
) but using the Delete method (DELETE /workbook/worksheets/{id|name}/tables/{id|name}) does work

Update table delete to match alternate in docs

---

O365/mailbox.py

fixed missing parentheses which throws an error when using default parameters. See github issue #332

fixed missing parentheses which throws an error when using default parameters

---

O365/connection.py

See [Endpoints for the APIs for Dynamics 365 Business Central On-Premises and Online](https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v1.0/endpoints-apis-for-dynamics) for additional details. This protocol can be used as an alternate protocol when using the financials endpoint.

Implement alternative Protocol for financials API

---

O365/utils/token.py
examples/token_backends.py

I've written this subclass example to work with your recent changes in the `Connection` class. This example works quite nicely, and successfully places all locking logic in the back end. Take a look and see what you think.
I also decided to remove `fs_wait` from the `FileSystemTokenBackend` - it didn't really make sense to have it there since that class will never be used in the scope of locking...it will always be subclassed, which is the more appropriate place for that attribute.
I'm not even sure it's really needed in the subclass - but I decided to leave it as maybe it could be helpful to be able to know the backend's "waiting" state.

add new LockableFileSystemTokenBackend example

---

O365/connection.py

Fix for #388 
This allows for a custom JSON encoder which is needed when using date and datetime objects. With this change you can do something like the following:
```
account = Account(credentials, scopes=settings.O365_SCOPES, token_backend=token_backend, json_encoder=MyJSONEncoder)
```
Where `MyJSONEncoder` could do:
```
import json
import datetime
class ComplexEncoder(json.JSONEncoder):
def default(self, obj):
if isinstance(obj, datetime.date):
return obj.isoformat()
return json.JSONEncoder.default(self, obj)
```

Allow for custom JSON Encoder class

---

O365/utils/token.py

Firestore client's collections() method doesn't take parameter
anymore. The collections() method can be replaced with collection
('collection_name') to get the required collection. Therefore,
fix this issue by replacing client.collections('collection_name')
with client.collection('collection_name') in the __init__ method
of FirestoreBackend.

FirestoreBackend: Replace client.collections() with collection()

---

O365/account.py
O365/teams.py
tests/test_teams.py

This is a start to adding Microsoft Teams support connected to issue #378. 
This adds basic support for creating channels, getting the logged in users teams, getting channel info and apps used within a team. I have not fleshed this out too much as most of the Teams endpoints are linked/rely on Groups so this may be something to look into in the future. 
As this is my first pull request I was not too sure about the library-style however as this is quite a basic change I was able to base the code heavily on planner.py.

Initial Microsoft Teams support

---

O365/drive.py

A small proposal to include a validation to convert_to_pdf:
- Raise ValueError if wrong file extension is given
- Make file extension validation on original file (`self.name`) and not on target file (`name`)
Especially, the last point gave me short headache since my target file name was obviously `name.pdf`, while `,pdf` is not included in the allowed extensions.
Hope it helps!
Best
Leander

Improve convert_to_pdf integration

---

O365/drive.py

The Graph API returns a path in the parent reference:
`
"parentReference": {
"driveId": "b!39YM7Ng72U...",
"driveType": "documentLibrary",
"id": "01CMZCJOWR....",
"path": "/drive/root:/FolderA/FolderB"
},`
Included a path attribute for drive items.

Add path attribute to drive item

---

O365/drive.py

Fixed indentation bug from #468 causing downloads of files with the `stream=True` to write no content.
Must be included in the same release as #468.

Fix no content on stream download

---

O365/excel.py

If running excel workbook in session mode, running the calculations should be done for the current session.
Without this fix, the API call is successful but it will not refresh any calculations for the sessions, so the session being worked on will never get recalculated.

Fix for running calculations when using sessions

---

O365/calendar.py

Fixed issue #382 "Recurring relative monthly events are wrongly classified as weekly", as lindera-steffen suggested.

Fixed issue #382

---

O365/drive.py

Thanks for your great work!
I used this library for a while and found a bug in drive client. Its `download_contents` does nothing for its child empty folder.
https://github.com/O365/python-o365/blob/master/O365/drive.py#L1145-L1150
```python
for item in self.get_items(query=self.new_query().select('id', 'size', 'folder', 'name')):
if item.is_folder and item.child_count > 0:
item.download_contents(to_folder=to_folder / item.name)
elif item.is_folder and item.child_count == 0:
if not to_folder.exists(): # <---- This line wants to create child folder of `item`, not `to_folder`
to_folder.mkdir()
else:
item.download(to_folder)
```

Fix bug: download_contents function does not create subfolder if it has no child.

---

O365/tasks.py
setup.py

This PR adds a read-only `importance` property as per https://docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-1.0#properties
Also, an experimentally established level "High" was found to match the MS To Do task when starred, and `is_starred` implements this heuristic.

Add Task.importance and Task.is_starred properties

---

O365/sharepoint.py

* Added build_field_filter helper function that will add fields to the query based on their internal name or display name
* Added expand_fields argument to get_items and get_item_by_id methods, if you pass True it will return all fields, if you pass a list of field names, it will filter as such

Add support for list item fields

---

O365/connection.py

The other day I have doing bulk operations via Graph API. My code is utilizing  python async with Multi process to achieve maximum speed. I occasionally run into the above mentioned issue and entire process would halt.

Fix for status code: 429 - Too many requests.

---

O365/mailbox.py

If a query has a limit which is bigger than the protocol's max_top_value than it only makes sense to batch it, and even more let the programmer decide the batch size.
Hope it doesn't break anything but it seems to me that if a batch argument can work with `limit = max_top_value  - 1` than it should also work with  `limit = max_top_value  + 1` .
Resolves #622

Use batch argument even when limit is huge

---

O365/drive.py

Starting today I started getting errors that looked like this:
```
copied_excel_file = operation.get_item()
File "/usr/local/lib/python3.7/site-packages/O365/drive.py", line 211, in get_item
self.item_id) if self.item_id is not None else None
File "/usr/local/lib/python3.7/site-packages/O365/drive.py", line 1599, in get_item
response = self.con.get(url)
File "/usr/local/lib/python3.7/site-packages/O365/connection.py", line 805, in get
return self.oauth_request(url, 'get', params=params, **kwargs)
File "/usr/local/lib/python3.7/site-packages/O365/connection.py", line 794, in oauth_request
return self._internal_request(self.session, url, method, **kwargs)
File "/usr/local/lib/python3.7/site-packages/O365/connection.py", line 756, in _internal_request
raise HTTPError('{} | Error Message: …
```

Fix for drive copy operation

---

O365/message.py
O365/utils/attachment.py

API Graph has a limitation of 4MB for each attachment.
The way to solve it is to create an upload session and PUT chunks of bytes until complete the file -> https://docs.microsoft.com/en-us/graph/api/attachment-createuploadsession?view=graph-rest-1.0&tabs=javascript
This change add support to files greater than 4Mb, it automatically check if the file to upload has more than 4Mb and choose this mechanism. 
I've taken some similar code from drive.py.

Create upload session for attachment in messages

---

O365/account.py
O365/utils/__init__.py
O365/utils/consent.py

This paves the way for more elegant alternatives for attaining a token using a consent URL. Example implementations would not be limited to using a web browser, a pyperclip copy, or a web browser combined with a custom redirect_uri and a temporary HTTP server on localhost.
The default and current consent process function is O365.utils.consent.consent_input_token.

Allow a dynamic consent process using functions

---

O365/utils/attachment.py

Just had a bug when attachment with size 3.8MB was throwing error
From official docs https://docs.microsoft.com/en-us/graph/outlook-large-attachments?tabs=http:
> - If the file size is under 3 MB, do a single POST on the attachments navigation property of the Outlook item; see how to do this for a message or for an event. The successful POST response includes the ID of the file attachment.
> - If the file size is between 3MB and 150MB, create an upload session, and iteratively use PUT to upload ranges of bytes of the file until you have uploaded the entire file. A header in the final successful PUT response includes a URL with the attachment ID.

Use upload session when attachment is larger then 3MB

---

O365/calendar.py

I have come accross small issue when trying to check if email is in the list of current attendees of event:
```
return item in {attendee.email for attendee in self.__attendees}
AttributeError: 'Attendee' object has no attribute 'email'.
```
When I checked the code "Attendee" indeed does not have attribute "email". 
It has attribute address instead. This PR provides a quick & easy fix for that.

calendar.py bugfix: AttributeError: 'Attendee' object has no attribute 'email'

---

O365/utils/attachment.py

This fixes an introduced bug where `_update_attachments_to_cloud` only
PUT the first part of an attachment and never resulted in assignment
of "on_cloud"

Bugfix: Short-circuit attachment upload when 201 created received

---

O365/drive.py

This is a fix for Issue #780
Without this fix when file is downloaded with convert_to_pdf == True - it downloaded with original extension (like .xlsx)
With this fix if convert_to_pdf == True extension of a file will be replaced with .pdf

bugfix for convert_to_pdf function

---

O365/connection.py

Since `requests_oauthlib.oauth2_session.OAuth2Session.fetch_token` and
`requests_oauthlib.oauth2_session.OAuth2Session.refresh_token` have
`verify=True` as the default value, `requests.sessions.Session` will give
more priority to the request's verify value (True) than the session's
verify value.

Make every request to honor the verify_ssl flag

---

examples/onedrive_example.py

Hello,
While using the OneDrive functionality of this library, I came across and attempted to use the example function `upload_file()` in `onedrive_example.py`, but kept getting an `IndexError: list index out of range` exception when attempting to upload to a file path that already existed. After diving into the code, I found the bug inside of the _get_child_folder() function that is called within the `upload_file()` workflow.
Currently, the function gets a list of `DriveItem`'s by calling `get_items()`, then parses the list to create a new list of names of child folders. It then checks if the desired folder name is in that list, and either returns it if so or creates a new one if not. The problem is, after iterating over the `items` list to check the names, it seems the list is somehow …

Updated _get_child_folder() function in onedrive_example.py

---

O365/message.py

update for issue: How to access "inferenceClassification" in msg object #804
We add a new instance attrib and create a new property for this attrib to be retrieved.

Add access to inferenceClassification in msg object

---

O365/account.py
O365/connection.py
examples/jwt_assertion.py

This method utilizes a JWT assertion to obtain the access token, as described in:
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow#second-case-access-token-request-with-a-certificate.
An example is also included with a helper to create the JWT assertion using the Private Key (PEM format), as described in: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-certificate-credentials
This helper uses pyjwt. Since we need to encode the assertion with RS256, the 'cryptography' module is also required, as described in: https://pyjwt.readthedocs.io/en/stable/usage.html#encoding-decoding-tokens-with-rs256-rsa

Add support for "certificate" authentication

---

O365/calendar.py
O365/utils/utils.py

According to this [issue](https://github.com/O365/python-o365/issues/838) (#838 ), the representation datetime of an all-day event was not correct as +3 house was added to an aware-datetime with the turkey timezone. This PR will resolve this issue.

fixed the all-day events time representation

---

O365/account.py
O365/tasks_graph.py
README.md

As promised here is a MS Graph api version of the Tasks/ToDo.
At this time, I've:
- implemented as a new class file `tasks_graph.py`, primarily because my formatting style on VSCode will re-format the rest of the code in `tasks.py`. I can copy the code into the original class file and rename the classes to names such as `ToDoGraph` if you wish.
- renamed a couple of attributes. (e.g. in the Graph api it uses `title` for the task, rather than `subject`). Also some constants are now all lower case (e.g. `Completed` has become `completed`).
- endpoints to constants - I'm paranoid about not matching things up. I can change back if preferred.
- tried to exercise all routes through the code. So hopefully no problems
- implemented a filter capability on `get_tasks` not present in existing code. …

Added support for tasks/todo via MS Graph API

---

O365/tasks_graph.py
README.md

Title is still used when accessing the MSGraph API.
As discussed. This should make it the same as MS Office API.
I think this may have undone one pep8 change.
Just to add - you have seen I have added filters. I've also add reminder time configuration

Rename title to subject as an attribute of task

---

O365/mailbox.py

There maybe a better way of doing this, but this adds the `/settings` endpoint rather that overriding the dictionary.

Correct setup of endpoints for Mailbox class

---

O365/mailbox.py

This PR:
- Types the input parameters so as to accept datetime objects for start and end date
- Accepts start date and end date as optional, so as to allow auto reply to be AlwaysEnabled or Scheduled.

Extend AutoReply Configuration

---

O365/connection.py
O365/mailbox.py
README.md

This PR extends the setting of auto_reply status, to setup for for full mailbox settings retrieval.
- Enables getting of autoreply settings as a subclass to mailbox settings (as it is in the MS Graph API - https://learn.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&tabs=http)
- Once retrieved, the settings can then be altered individually.
- Alters mailbox.set_automatic_reply/set_disable_reply to use the new classes, but does not alter the external calls to those methods
This should be easily extensible to retrieve all mailbox settings.
**Query** I've set the automaticrepliessettings class to be an ApiComponent. It has no direct api calls through it, they are all handled at MailboxSettings, so not sure if it needs to be an ApiComponent, but had to set it that …

Extend mailbox settings

---

O365/mailbox.py
O365/utils/utils.py

According to Graph API docs (https://learn.microsoft.com/en-us/graph/api/resources/mailfolder?view=graph-rest-1.0) there are multiple more Well-Known Folder names than implemented. This PR is to get the library synchronized with GraphAPI capabilities. 
Adding missing defininitions for folders:
```python
CLUTTER='clutter'
CONFLICTS='conflicts'
CONVERSATIONHISTORY='conversationhistory'
LOCALFAILURES='localfailures'
RECOVERABLEITEMSDELETIONS='recoverableitemsdeletions'
SCHEDULED='scheduled'
SEARCHFOLDERS='searchfolders'
SERVERFAILURES='serverfailures'
SYNCISSUES='syncissues'
```

Adding remaining well-known folder names.

---

O365/excel.py

in excel.py -> Table -> update(), if show_headers or show_totals is False, then it won't be added into request, mentioned in [Issue 937](https://github.com/O365/python-o365/issues/937)

fix the bug can not update Table show_headers and show_totals of Table

---

O365/utils/windows_tz.py

Renamed "Europe/Kiev" to "Europe/Kyiv" as per ICANN's change: https://mm.icann.org/pipermail/tz-announce/2022-August/000071.html
Fixes error when using calendar with timezone "Europe/Kyiv":
`pytz.exceptions.UnknownTimeZoneError: "Can't find Iana TimeZone Europe/Kyiv"`

Rename UA Kyiv timezone

---

O365/calendar.py

Adds `hex_color` property to `Calendar()`. If a user sets a custom calendar color on outlook.com, currently `Calendar()` will call `CalendarColor.from_value(color)` to convert it to a pre-defined color, but there are use cases where getting the actual color id is better suited. `hexColor` is a defined property according to https://learn.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0, and it is readily available for querying `cloud_data = ['id', 'name', 'color', 'hexColor', 'isDefaultCalendar', 'changeKey', 'canShare', 'canViewPrivateItems', 'canEdit', 'allowedOnlineMeetingProviders', 'defaultOnlineMeetingProvider', 'isTallyingResponses', 'isRemovable', 'owner']`

Add Calendar().hex_color property

---

O365/excel.py

Hi - it seems that the format key was missing for building the url for invoke_function.  This makes it work for me.

add missing format keyname for invoke_function endpoint

---

O365/message.py

Added single_value_extended_properties instance attribute and property so singleValueExtendedProperties can be accessed. This allows you to get information like the message size (singleValueExtendedProperty id LONG 0x0E08)

Add access to singleValueExtendedProperties in Message

---

O365/account.py

When authenticating with "credentials", "certificate" or "password", there is no way to control the behaviour of `request_token` by passing extra keyword arguments. This is already possible for "authorization" and "public" authentication types.
This PR fixes that by passing the keyword arguments also when auth_flow_type in "credentials", "certificate" or "password".

Pass keyword arguments to request_token also when auth_flow_type is credentials, certificate or password

---

O365/utils/utils.py

The required zoneinfo.Zoneinfo is key, not name.
The parameter name can be ommited.

fix(zoneinfo): Fix #1005, no argument call name for Zoneinfo

---

README.md

Readme listed python support >= 3.4, but setup.py states >=3.9. Updated readme to reflect setup.py.
Fixes (at least) #890 #880

Update readme supported python version to match setup.py

---

O365/drive.py

to address [this issue](https://github.com/O365/python-o365/issues/872#:~:text=The%20monitor%20url,the%20monitor%20request.) where the checking of the copy operation fails because the request is sent with Auth headers when not required. Feels more like a bug on the Microsoft API that they should ignore these headers when dealing with the requests (or update their docs...)

Send naive request to monitor url

---

O365/teams.py

Add ability to set user presence status per application and set user preferred presence status, plus get another users presence status
Get my presence status is currently under Teams, so I have placed these there as well

Add ability to set user status and get another users status

---

O365/calendar.py

Converts date objects into datetime objects in Event.get_occurrences() to add missing time parameters
```
File "/var/www/domain.tld/backend/.venv/lib/python3.11/site-packages/O365/calendar.py", line 1378, in get_occurrences
if start.tzinfo is None:
^^^^^^^^^^^^
AttributeError: 'datetime.date' object has no attribute 'tzinfo'
```

Fix get recurring instances events invalid start/end time bug

---

O365/connection.py

Added support for multiple Prefer headers in the Connection class. 
Clarified unsupported method error message.
Assuming something like: 
```
schedule = Schedule()
schedule.con.default_headers['Prefer'] = 'IdType="ImmutableId"'
```
Using a method that has a Prefer header hardcoded in the request, like Calendar.get_event() which specifies `response = self.con.get(url, params=params, ={'Prefer': 'outlook.timezone="UTC"'})` would override `Connection.default_headers['Prefer']`. This change concatenates the values.
Before:
```
2024-01-11 11:38:04,410 DEBUG    Supplying headers {'Prefer': 'outlook.timezone="UTC"}
```
After:
```
2024-01-11 11:38:04,410 DEBUG    Supplying headers {'Prefer': 'outlook.timezone="UTC", IdType="ImmutableId"'}
```
Assuming something like:
```
_allowed_methods = …
```

Add support for multiple Prefer headers in Connection class

---

O365/mailbox.py

For some applications that rely on user information to provide functionality, it is helpful to retrieve user data, such as the user's time zone and working hours, directly from the Microsoft Graph API instead of asking the user for this information.
The current implementation of MailboxSettings does not expose the user's  time zone & working hours even though the information is retrieved from the Microsoft Graph API by the code.
This PR exposes the timeZone and workingHours mailbox settings to the user as class variables in the MailboxSettings class.
This functionality will help in the development of  [AdminGPT](https://github.com/sdelgadoc/AdminGPT) an AI-powered administrative assistant, implemented using OpenAI's Assistant framework to seamlessly integrate with your email and calendar. …

Added time zone & working hours to MailboxSettings class

---

O365/calendar.py

Adds webLink property from Event spec: https://learn.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0

Add web_link property to Calendar

---

O365/excel.py

Currently for the Excel.Range.get_used_range() and Excel.WorkSheet.get_used_range() methods, they do not work with the MS Graph API parameter "onlyValues" (for considering only Excel cells with values/ignoring empty but formatted cells).
The Excel.Range.get_used_range() method currently has an "only_values" parameter, but the Excel.Range endpoint for "get_used_range" currently does not have the "onlyValues" parameter included. So I have updated that endpoint. And since the Excel.Range.get_used_range() already has the "only_values" parameter set to default as True, I left that unchanged.
The Excel.WorkSheet.get_used_range() does not have an "only_values" parameter, so I added it. And similarly, the Excel.WorkSheet "get_used_range" endpoint also currently lacks the "onlyValues" parameter, …

Update Excel get_used_range methods to fix/enable "onlyValues" API parameter

---

O365/tasks.py
O365/tasks_graph.py

Currently only derived fields are exposed, e.g. is_complete. However status can have multiple values, so should be exposed directly.

Expose task status

---

O365/message.py
tests/test_message.py

This a continuation on an existing PR #871 , and tries to handle the comments there. Also adding the property before the `restrict_keys` part to not sidestep that functionality.
We want to be able to send custom headers to the email, as supported in [this example i MS docs](https://learn.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&tabs=http#example-2-create-message-draft-that-includes-custom-message-headers). 
I added two unit tests to verify the behavior ~but I wasn't able to test it with the live environment~. I've tested it with my O365-account and I think it works as expected.

Add custom headers to email

---

O365/utils/utils.py
tests/test_recipient.py

- Added angled brackets instead of braces to repr of recipient
- Decided against adding quotation marks around the name part, as this isn't done by the built in `imap`/`email` representation either.
- Added unit tests to test stringifying recipient

Added angled brackets instead of braces to repr of recipient

---

O365/excel.py

Table Row operations are not aligned anymore with Microsoft Graph Docs 
https://learn.microsoft.com/en-us/graph/api/tablerowcollection-itemat?view=graph-rest-1.0&tabs=http
See also here, but this did not fully fix the issue
https://github.com/O365/python-o365/pull/849
could you please review and merge if this is fine?

fixing itemAt endpoint to new structure

---

O365/directory.py

The User object has everything I need... except the ability to access the onPremisesSamAccountName to be able to integrate with on-prem applications.
I feel like I agree with [this comment](https://github.com/O365/python-o365/issues/298#issuecomment-528493118) of having a way of providing access to these sort of 'niche' attributes without needing to modify the object - perhaps just exposing a way to accessing the cloud data - but I can't see a way of achieving this with the current code, so here is a pull request to provide access to my new niche attribute :)

User: add ability to access onPremisesSamAccountName

---

O365/utils/__init__.py
O365/utils/token.py

**Background**
Python Django is a popular web development framework. It provides a flexible database interface that supports various types of databases. When developing Django applications, it is best practice to store non-volatile data in the Django database using its interface.
**Challenge**
Current TokenBackend implementations do not support the Django database interface directly, nor provide a compatible interface for use with Django.
**Changes**
This PR introduces the `DjangoTokenBackend` class, which extends `BaseTokenBackend` to support storing tokens in a Django database. It also updates `__init__.py` to make it easier for users to load `DjangoTokenBackend`.
**Appendix**
This functionality will assist in the development of [AdminGPT](https://github.com/sdelgadoc/AdminGPT), an …

Add DjangoTokenBackend to Support Django Database for Token Storage

---

docs/source/getting_started.rst

**Background**  
One of the biggest barriers for beginners to get started with the python-o365 library is setting up OAuth authentication. The “Getting Started” guide referenced the outdated `apps.dev.microsoft.com` portal, could include additional detail, and did not include an example of how to use the library. In addition, other tools that use the python-o365 library can benefit from improved getting started instructions.
**Challenge**  
With the transition to the Microsoft Entra Admin Center, the old instructions might confuse users by pointing them toward a deprecated portal. A more detailed guide could help developers navigate the new Microsoft Entra Admin Center and quickly understand python-o365 installation and usage.
**Changes**  
- **Updated Microsoft Entra Admin Center …

Updated "Getting Started" documentation

---

CHANGES.md

I've added some extra items which you can include or exclude as you like

Suggested changes to changlog

---

O365/connection.py

Up to you if you merge this or not. You may be aware of something that will cause a problem.
Relates to this issue - https://github.com/O365/python-o365/issues/1130

Remove call to get_local_zone() if not required

---

O365/calendar.py

I believe this resolves issues #947 and #697 
Tested on 12k events across many different calendars.
Changed behavior so when a private event is encountered, response_status and body are set to be an empty dictionary instead of None.
This is my first public contribution so please let me know of any miss-steps, thanks!

FIX: Handles private events with missing properties

---

O365/utils/token.py

As outlined in #1142 this adjusts the Bitwarden SDK call to the new method call.

Fix for changed BW SDK call

---

O365/connection.py
examples/token_backends.py

I've made two modifications to this, one in connection.py and one in the examples. Both of these I have tested through, and without the changes I get 401 errors.
connection.py - I've changed the method of how the 401 error is ignored. This is because in my app, multiple threads are using the same account/connection object, so the existing flag was already set to True for any threads after the first that were doing a query. What I believe is required is that all queries get two chances in `oauth_request`, so the first call to `_internal_request` should 'ignore' a 401 and raise a TokenExpiredError, and the second call should raise the 401 error if repeated.
token_backends.py - The existing example did not loop (default max 3 times) while the second thread (when finding the file locked) …

Modify to handle threads using same account/connection object

---

O365/utils/utils.py

https://github.com/O365/python-o365/issues/684
In support of this issue, this adds the ability to convert a select attribute from a simple attribute to a complex one required by MS Graph.

Add mapping for complex attributes

---

O365/calendar.py

schedule.get_events calls calendar.get_events and so needs the start/end parameters adding as well.

Add start/end parameters to schedule.get_events

---

O365/__init__.py
O365/address_book.py
O365/connection.py
O365/excel.py
O365/groups.py
O365/message.py
O365/planner.py
O365/utils/utils.py
README.md
docs/source/usage/connection.rst
setup.py

Office 365 api is no linger available from Microsoft, so this PR is to remove it. If you disagree, then feel free to reject.
I've also change mention of Office 365, (where it does not relate to the Office 365 API), to Microsoft 365 in line with current MS branding.

Remove Office 365 Protocol and documentation

---

O365/calendar.py

In support of this issue - https://github.com/O365/python-o365/issues/1168 - this enables full query support on list_calendars. Currently the string of the query is used `str(query)`. I don't know if this will break existing usages, but it seems incorrect to not have full query support.
New code is:
```python
if query:
if isinstance(query, str):
params["$filter"] = query
else:
params.update(query.as_params())
```

Add ability to use full query to list_calendars
