O365/python-o365

O365/cal.py
Just some minor fixes for typo's and comments are now like this:
#&nbsp;Text
in place of:
#Text
PEP8 likes this more.
=> [IMP] Spelling and formatting corrections

O365/inbox.py, tests/test_inbox.py
Just made two small modifications that append the '$top' parameter to the messages request, and ensure that the inbox test will continue to pass after this change.
=> Support pulling more than 10 messages.

O365/message.py
Added getID and getReceivedDate to message.py
=> Added getID and getReceivedDate to message.py

O365/event.py
Because it was hardcoded first, i kept the default ContentType
=> Enable us to change theContentType of the body

O365/message.py
Dear Narcolapser:
I want to add the feature of sending from other mail if the user have permissions, I've already created the fork, please change whatever you need. The extra code has been tested.
I'll be waiting for your comments.
Best regards
Blastter
=> Send as another email if you have permisions. TESTED

.gitignore, O365/event.py
Fails when upstream server returns http code > 399  and print response body
Added intelij to gitignore
=> Event creation enhancement

O365/attachment.py
Attempt to fix issue #72 with the Value Error. More testing needed.
=> Exception handling (ValueError) in getType()

O365/fluent_inbox.py, O365/fluent_message.py, examples/FolderOperations/get_folder.py, examples/FolderOperations/list_folders.py, examples/FolderOperations/trash_message.py
Great module!  This is a pull request to add a couple extra capabilities in for working with moving messages between folders (Like 'Trash').  Thanks!
=> Adding in operations to do more with folders

O365/inbox.py, setup.py
should address at least the specific problem reported in #86, larger scale checks should be done.
=> fixing tabs in inbox.py

O365/message.py, tests/test_message.py
Methods to set and get email categories. Tested on actual emails successfully.
(and my editor felt like stripping some whitespace in the tests file)
=> Add message methods for categories

O365/fluent_message.py, README.md
@Narcolapser another one :) 
* Send as/from shared mailbox
* Some readme notes on above and `FluentInbox` shared inbox support
* My editor trimmed some trailing whitespace automatically..
Again, would be awesome if we could get a new release on PyPI 🚢
=> Added support for sending from shared mailbox

O365/cal.py
This way a user can simply print a calendar name.
=> Add __str__ method to cal

O365/fluent_inbox.py, examples/FolderOperations/search_subfolders.py
Added parent_id as argument to FluentInbox.from_folder method, added FluentInbox.folder attribute to store current folder and make it easier to get its folder info, like Id. Added example file illustrating how to navigate and get messages from inbox down to a nested subfolder.
=> Improved subfolder navigation

O365/message.py
=> Misspelling

examples/calendarCookbook.py
Sample script to demonstrate how to pull calendar names and event names. Quick demonstration of how to use the built-in functions.
=> Calendar Pull Sample

README.md
changed pyo365 to O365 since it caused me a lot of Confusion during the Implementation because I installed the pyo365 package
=> Updatet package name in readme

README.md
The updated calendar example in the README was not working for me (400 bad request) - I changed to first call get_default_calendar and then call new_event() on that and that worked - also kicked it into the future by adding a year :-)
=> Updated calendar example code 

O365/__init__.py, O365/account.py, O365/planner.py, tests/test_planner.py
PR for planner related features like tasks
=> Planner and tasks

O365/__init__.py, O365/account.py, O365/connection.py, O365/planner.py, O365/sharepoint.py, O365/utils/__init__.py, O365/utils/token.py, README.md
Improvements on authentication and other improvements
=> Authentication & other improvements

examples/storageDownloadFile
I created this sample to help me understand how to use your module. Thought I'd pull in case it helps others.
=> Added a storage sample 

O365/calendar.py
=> fix broken URL for accepting an event

O365/sharepoint.py
Removed the list iteration that returns from list_by_name of the class Site.  When passing a list name only one response is to be expected.
Closes #209
=> Removed list iteration in list_by_name of Site

O365/sharepoint.py
Good news is that I am making progress on some sharepoint documentation...
Bad news is I found a bug that I put into the sharepoint code with the feature additions.
Bug is in regards to not importing TrackerSet from utils in the version that made it to the Pull Request.
=> Fixing bug of not importing TrackerSet

O365/connection.py
added None check to data before json conversion.
json converts None into 'null' which is not a valid json
=> fixed empty post data error

O365/connection.py, README.md
- get_authorization_url() returns a (url, state) tuple
- get_session() takes additional parameters to (re)create sessions
- refactored internals to use get_session(), ensuring consistency
=> Changes required for web-flow authentication:

O365/drive.py
Allows for getting a specific file or folder from a drive or document library using the syntax:
`Drive.get_item_by_path('/path/to/item')`
=> Add Drive.get_item_by_path(item_path)

O365/message.py, O365/sharepoint.py, O365/utils/utils.py
I found these features to be necessary while working with a rather large list.
=> Add pagination return and ability to pass query to SP list's get_items().

README.md
The onedrive example is wrong.
=> Fix bad onedrive example

O365/utils/utils.py
Added `on_list_field` method to the `Query` class in order to correctly filter a SharePoint list by its fields.
=> Added field query for SharePoint lists.

O365/teams.py
The class attribute is display_name, not displayName.
=> Fix team displayName -> display_name

docs/source/usage.rst, docs/source/usage/sharepoint.rst
Here is the first pass at the Sharepoint docs.  I have the HTML build from make html output, but I was not sure how you wanted to review the proposed documentation, and if there was already a process in place to build the new documentation.
After you review, just let me know if you want me to add in the entire HTML build output, parts of it, or just these .rst file changes if you had plans on making other updates to the docs.
=> Sharepoint Docs Draft

O365/account.py, O365/connection.py
Added ability to request token without supplying client secret by setting auth_flow_type to 'public'
=> Public Client

O365/drive.py
I've added the ability to pass in io objects to write to/read from in the file upload and download, in addition to the filename.  This allows easier integration with the project I'm working on.
=> Add upload and download stream option

O365/drive.py, README.md
updated to reflect that getting items with drive API returns generator not a list
=> Fix onedrive readme example

O365/drive.py
Main change / new 'feature':
- Added an input argument that can be used to control the conflict handling when uploading a file in chunks.
Smaller changes:
-  Fixed the parameter name `item_name` so the documentation fits the actual input argument
-  Added one sentence to chunk_size so it's clear when it will be relevant.
The default now overwrites a file (despite MS docs saying it will fail), without raising errors which seems error-prone to me.
(see [MS docs](https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0#create-an-upload-session) for the official documentation)
This option is sadly unavailable for non-resumable sessions as of now (not implemented in Graph API)
Not entirely sure on how you like to use naming/explanations at the moment so …
=> Conflict handling support for upload_file

O365/calendar.py
I would like to add a Teams meeting and request this pull request.
https://docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta
=> add online_meeting methods

O365/connection.py
Need this to override file path/name of the token.
=> Update connection.py to pass kwargs to FileSystemTokenBackend

O365/account.py, O365/connection.py, O365/tasks.py
I've added basic support for Outlook Tasks, based on the existing Calendar architecture. All of the basic task functionality offered by the MSOffice365 API is supported including:
- Addition or removal of tasks and folders
- Completing or uncompleting tasks
- Setting due dates
However, attachments and reminders are not yet supported. The MSGraph API for tasks [here](https://docs.microsoft.com/en-us/graph/api/resources/todo-overview) is still in beta so I haven't bothered to add support for this yet. I've successfully used this implementation to migrate all my tasks from Todoist over to Microsoft Todo.
=> Tasks support

README.md
Explain new tasks API and provide examples.
=> Update README.md with tasks section

O365/drive.py
Fixed: Crashes when trying to download contents from a folder that has an empty folder.
=> FIX: drive.py

O365/utils/token.py
I propose adding [AWS Secrets manager](https://aws.amazon.com/secrets-manager/) as a backend for token storage.
=> Add AWS Secrets Manager Token Backend

O365/calendar.py
Fixed Issue https://github.com/O365/python-o365/issues/553
=> Fixed Issue #553

O365/connection.py, tests/test_protocol.py
* Update `TEST_SCOPES` in protocol unit test with additional scopes
* Used `if hasattr(self, 'attr'):` instead of `if self.attr:` as I was getting an `AttributeError`
=> Update TEST_SCOPES in protocol unit test with additional scopes

O365/connection.py, O365/utils/token.py, README.md
Changed f-strings to traditional `string.format` method in order to remain compatible with 3.4+
=> Remove f-strings

O365/drive.py
=> Allow pulling of DriveItems external to tenant

O365/message.py
I ran some performance tests on this library and found a performance improvement that's easy to fix.
Instead of checking if there are attachments for every message I changed the `has_attachment` property to be 'lazy'.
Thanks guys, keep up the great work!
=> message: Check if attachments exists lazily

O365/teams.py, O365/utils/utils.py
I added a few things I noticed were missing when working with Teams; primarily the ability to work with chats and messages.
=> Add Chat and Message Support in Teams

O365/account.py, O365/groups.py
I needed to get o365 group members, so I wrote "groups" module.
Only GET methods implemented because I have only Read permissions in my organization.
=> Added some O365 Group functionality

README.md
'aims is' -> 'aims' && 'interact' -> 'interacting'
=> Typo in readme first line

O365/directory.py, O365/groups.py
- added retrieving group by its mail field
- removed retrievieng group by its nickname field (it hadn't worked at all)
- added getting group members with "recursive" flag -> if group member is another group then get members of child group too
=> Group class enhancements

O365/teams.py, O365/utils/utils.py, tests/test_teams.py
I added a few methods to the teams module and streamlined the resource parsing a bit.
=> fix teams resource parsing

O365/utils/utils.py
To enable filtering on body/content
=> Add mapping for 'body'

O365/teams.py
When calling get_all_chats it does not paginate like the other get_all_XXX functions.  I copied the code from those and modified it for the correct endpoint to get all chats with pagination
=> add pagination to get_all_chats

O365/connection.py
Allows user to set and http url for both http and https requests.
There are organizations and users that only have an http proxy instead of a proxy that does ssl intercept.
Fixes #616
=> added proxy_http_only flag for Connection

O365/sharepoint.py
=> Fix SharePoint `search_site` with more than 200 results

O365/planner.py
update fixed, before it was not able to update with an empty list or dict. plus some adjustments
=> bug fix on update method

O365/planner.py
Adds Pagination return to Plan's list_tasks method to allow the return of all tasks instead of only 400 (endpoint limit). Also, it appears the endpoint doesn't support the "$top" query parameter.
=> add Pagination to Plan.list_tasks

O365/calendar.py
Added endpoint "create_upload_session" missing in "EventAttachments" class
=> Fix issue #861

O365/mailbox.py, examples/automatic_response_example.py
These changes allow to set/ disable the auto reply.
With this you can schedule the auto reply functionality in outlook
=> Added ability to set/ disable auto reply

O365/mailbox.py
I forgot to add externalAudience
=> Added externalAudience

O365/mailbox.py
Sorry, spotted a small issue. Could be handled in the calling code, but tidier here.
=> Minor change to handle empty externalAudience

O365/connection.py
Allow to set default_headers when creating account so that those params are sent.
Typical usage is default_headers={"Prefer": 'IdType="ImmutableId"'} which allows to have permanent immutable id instead of default temporary ID which changes as soon as the object (message / event / task / contact) gets moved / updated.
=> Update connection.py to allow default_headers to allow immutable ID

O365/connection.py, O365/utils/utils.py
Added extra mapping in Utils to support filter by due datetime and reminder datetime in Tasks
Also added extra detail to connection error reporting <-- This can be removed if preferred but it provides extra information on why a call failed.
=> Add support for filter by due datetime in Tasks

O365/connection.py
This pull request can solve the issue of #992
=> ✨ pass all arguments to create authorization URL

O365/address_book.py
Adds fileAs attribute to addressbook
=> Add fileAs attribute to addressbook

O365/address_book.py
This is a rather simple change that would fix issue #989.
=> Fix typos causing home address to be unretrievable.

README.md
This fixes #509 by updating the documentation.
=> Update documentation to close #509

O365/message.py
This push is to add a feature where people can read the contents of the email type attachments.
Current code base supports only saving of the email type attachments, but there may be cases where people might want to read the content of the email type attachments for further processing. This push exactly adds that feature.
=> To solve issue #1025 (Being able to read mime content of .eml or .msg type attachments)

O365/drive.py
method `CopyOperation.get_item` only worked if the copied item was copied to the same location as the original item. Here we introduce the optional argument target which defaults to the parent if not given (i.e. the scenario where we copy to the same location as original item) so that the copied item can be successfully retrieved from it's new location upon successful copy completion. 
https://github.com/O365/python-o365/issues/872 
Also, update mistake in comment on parent type in the init
=> Fix bug with `get_item` on `CopyOperation`

O365/drive.py
https://learn.microsoft.com/en-us/graph/api/resources/file?view=graph-rest-1.0
relates to https://github.com/O365/python-o365/issues/794
=> Added hashes to File class

O365/drive.py
=> add slash if missing

O365/planner.py
=> added bucket_id to allowed update-attributes of Task

O365/planner.py
Fix #1022 
(simple typo i guess ;) )
=> fix KeyError in planner taskDetails creation

README.md
Per @alejcas request in PR https://github.com/O365/python-o365/pull/1116, I am adding the app registration steps in the Getting Started documentation to the README.
=> Added app registration steps to README

pyproject.toml
=> Add dynamic values

README.md
I was creating a new app in Entra, and realized that one critical step was missing. This is a small change, but will likely stop folks from being able to setup the authentication.
=> Added in README necessary step to set app to "Multitenant"

O365/utils/token.py, docs/source/api/utils.rst, docs/source/api/utils/token.rst, docs/source/usage/utils.rst, docs/source/usage/utils/token.rst, docs/source/usage/utils/utils.rst
I've added limited usage information, should be enough to get someone started.
=> Add docs for token

O365/message.py
https://github.com/O365/python-o365/issues/1086
=> Fix CC email address not remove

O365/calendar.py
https://github.com/O365/python-o365/issues/1117
=> Add transaction_id

O365/calendar.py
https://github.com/O365/python-o365/issues/545
=> Add recurrence type as output field

O365/groups.py
https://github.com/O365/python-o365/issues/1091
=> Add pagination for get_user_groups

O365/tasks.py
https://github.com/O365/python-o365/issues/1072
=> Add support for checklist items with To-Do tasks

O365/utils/query.py, O365/utils/utils.py
I'll try to do some testing of more of the new query builder
=> Handle meetingmessagetype

O365/connection.py
Pull request to address this issue - https://github.com/O365/python-o365/issues/1174
=> Ignore 403 as well as 401

docs/latest/_sources/getting_started.rst.txt, docs/latest/getting_started.html, docs/source/getting_started.rst, pyproject.toml, setup.py
Removed python 3.9 from config files. I believe this is all that is needed, let me know if more required.
=> Remove support for Python 3.9

docs/source/usage/sharepoint.rst
Just noticed a minor change needed in sharepoint docs
=> Minor docs change
